spring.application.name=levExpress
zeebe.client.cloud.region=bru-2
zeebe.client.cloud.clusterId=dfdb8d36-5bf6-4b20-be42-8205ce0805f0
zeebe.client.cloud.clientId=V5ZGsVGRYTtm4LVI1sjWu6YDqXdrIEkh
zeebe.client.cloud.clientSecret=c8dZEw_dxNe7PfbLVD8Qa5wRbMk2EPNnrY8kz~512~.fno0fvQ2PLp-kWsjgwUcT
zeebe.client.worker.default-name=levExpressV2